# Toronto Crime Data Exploration

This notebook explores the Toronto crime datasets before cleaning and formal analysis.

The goals are to:
- understand the structure of each dataset
- identify missing values and duplicates
- inspect important variables
- compare crime rates across neighbourhoods
- examine patterns over time
- identify cleaning decisions needed before analysis

### Importing Libraries

In [57]:
# Data manipulation and visualization libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### Loading Initial Data

In [34]:
crime = pd.read_csv("../data/raw/neighbourhood-crime-rates - 4326.csv")

### Basic Data Exploration

In [58]:
# # Show rows and columns count
print(f"Rows count: {crime.shape[0]}\nColumns count: {crime.shape[1]}")

Rows count: 158
Columns count: 221

In [59]:
crime.head()

,_id,AREA_NAME,HOOD_ID,ASSAULT_2014,ASSAULT_2015,ASSAULT_2016,ASSAULT_2017,ASSAULT_2018,ASSAULT_2019,ASSAULT_2020,...,THEFTOVER_RATE_2018,THEFTOVER_RATE_2019,THEFTOVER_RATE_2020,THEFTOVER_RATE_2021,THEFTOVER_RATE_2022,THEFTOVER_RATE_2023,THEFTOVER_RATE_2024,THEFTOVER_RATE_2025,POPULATION_2025,geometry
0,1,South Eglinton-Davisville,174,55,56,66,73,74,62,74,...,13.797544,13.097577,16.740604,24.216984,11.665436,29.499613,21.188684,20.759809,28902,"{""coordinates"": [[[[-79.3863542900264, 43.6978..."
1,2,North Toronto,173,53,57,47,61,66,84,80,...,36.176834,26.750484,43.862396,11.872959,22.540291,36.945164,30.007502,24.293072,20582,"{""coordinates"": [[[[-79.3974398976879, 43.7069..."
2,3,Dovercourt Village,172,62,65,92,105,106,113,91,...,29.658190,29.775198,22.602276,15.283509,30.555344,22.610792,52.426601,22.850180,13129,"{""coordinates"": [[[[-79.4341164165158, 43.6601..."
3,4,Junction-Wallace Emerson,171,164,159,171,161,163,186,171,...,36.188179,15.985932,36.070698,32.293224,31.383625,33.834587,47.279606,32.400906,27777,"{""coordinates"": [[[[-79.4387032547807, 43.6676..."
4,5,Yonge-Bay Corridor,170,387,521,481,602,576,660,377,...,346.893738,478.723419,258.569733,187.630798,351.821198,337.443207,296.040466,210.071426,16661,"{""coordinates"": [[[[-79.3840431592607, 43.6449..."

In [61]:
crime.tail()

,_id,AREA_NAME,HOOD_ID,ASSAULT_2014,ASSAULT_2015,ASSAULT_2016,ASSAULT_2017,ASSAULT_2018,ASSAULT_2019,ASSAULT_2020,...,THEFTOVER_RATE_2018,THEFTOVER_RATE_2019,THEFTOVER_RATE_2020,THEFTOVER_RATE_2021,THEFTOVER_RATE_2022,THEFTOVER_RATE_2023,THEFTOVER_RATE_2024,THEFTOVER_RATE_2025,POPULATION_2025,geometry
153,154,West Humber-Clairville,1,289,306,291,301,314,255,248,...,144.574219,182.558624,157.201813,152.014191,169.571625,213.941391,188.980576,245.949844,37406,"{""coordinates"": [[[[-79.5903745028226, 43.7340..."
154,155,Black Creek,24,222,226,279,246,199,216,269,...,35.315411,39.691292,70.950287,40.308132,35.506634,56.340469,51.222946,47.307758,23252,"{""coordinates"": [[[[-79.5191491527649, 43.7739..."
155,156,Pelmo Park-Humberlea,23,58,45,59,53,73,77,54,...,35.014004,60.111637,85.106384,16.957775,74.943794,48.453526,55.296627,86.949646,12651,"{""coordinates"": [[[[-79.532254418425, 43.73505..."
156,157,Humbermede,22,105,128,106,150,107,150,84,...,58.979652,46.093571,56.798817,73.136429,49.398979,52.873684,41.097298,71.505180,19579,"{""coordinates"": [[[[-79.5281298918329, 43.7442..."
157,158,Humber Summit,21,90,98,127,121,120,130,100,...,115.973404,169.478470,177.949707,226.120865,178.585297,320.243988,135.869568,191.073059,13084,"{""coordinates"": [[[[-79.5339680482543, 43.7688..."

#### Check Data Types

In [78]:
crime.dtypes

_id                      int64
AREA_NAME                  str
HOOD_ID                  int64
ASSAULT_2014             int64
ASSAULT_2015             int64
                        ...
THEFTOVER_RATE_2023    float64
THEFTOVER_RATE_2024    float64
THEFTOVER_RATE_2025    float64
POPULATION_2025          int64
geometry                   str
Length: 221, dtype: object

- `AREA_NAME` and `GEOMETRY` are strings.
- `_id`, `HOOD_ID`, `POPULATION`, and **crime counts** are integers
- **Crime rates** are floats.

#### Check for Missing Data

In [118]:
crime.isna().sum().sum()

np.int64(4020)

#### Check for Duplicate Rows

In [86]:
print("Crime duplicates:", crime.duplicated().sum())

Crime duplicates: 0

#### Areas to Fix

The neighbourhood crime dataset contains missing values (NaN) for homicide and shooting counts in 2025. Since these variables are important to the analysis, separate Toronto Police homicide and shooting datasets are used to investigate and reconstruct the missing information.

### Supplementary Homicide and Shooting Data Exploration

#### Loading Additional Datasets

In [54]:
homicide = pd.read_csv("../data/raw/Homicides - 4326.csv")
shooting = pd.read_csv("../data/raw/shootings-firearm-discharges - 4326.csv")

#### Homicide Data Exploration

In [89]:
## Show rows and columns count
print(f"Rows count: {homicide.shape[0]}\nColumns count: {homicide.shape[1]}")

Rows count: 1542
Columns count: 17

In [90]:
homicide.head()

,_id,EVENT_UNIQUE_ID,OCC_DATE,OCC_YEAR,OCC_MONTH,OCC_DAY,OCC_DOW,OCC_DOY,DIVISION,HOMICIDE_TYPE,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84,geometry
0,1,GO-2004111878,1073106000000,2004,January,3,Saturday,3,D53,Other,098,Rosedale-Moore Park (98),098,Rosedale-Moore Park (98),-79.392828,43.685026,"{""coordinates"": [[-79.3928283609999, 43.685026..."
1,2,GO-2004136086,1073538000000,2004,January,8,Thursday,8,D42,Shooting,146,Malvern East (146),132,Malvern (132),-79.205574,43.810544,"{""coordinates"": [[-79.205574184, 43.810544206]..."
2,3,GO-2004125755,1073538000000,2004,January,8,Thursday,8,D42,Shooting,142,Woburn North (142),137,Woburn (137),-79.233852,43.781782,"{""coordinates"": [[-79.233852025, 43.781781696]..."
3,4,GO-2004148623,1075006800000,2004,January,25,Sunday,25,D13,Shooting,171,Junction-Wallace Emerson (171),093,Dovercourt-Wallace Emerson-Junction (93),-79.434387,43.670467,"{""coordinates"": [[-79.434387326, 43.670467021]..."
4,5,GO-2004148619,1075006800000,2004,January,25,Sunday,25,D42,Shooting,144,Morningside Heights (144),131,Rouge (131),-79.204958,43.822997,"{""coordinates"": [[-79.204958114, 43.8229965730..."

In [91]:
homicide.tail()

,_id,EVENT_UNIQUE_ID,OCC_DATE,OCC_YEAR,OCC_MONTH,OCC_DAY,OCC_DOW,OCC_DOY,DIVISION,HOMICIDE_TYPE,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84,geometry
1537,1538,GO-20261126610,1780200000000,2026,May,31,Sunday,151,D23,Shooting,001,West Humber-Clairville (1),001,West Humber-Clairville (1),-79.603441,43.719267,"{""coordinates"": [[-79.603441295, 43.719266949]..."
1538,1539,GO-20261207010,1781150400000,2026,June,11,Thursday,162,D12,Shooting,030,Brookhaven-Amesbury (30),030,Brookhaven-Amesbury (30),-79.490152,43.696437,"{""coordinates"": [[-79.490152066, 43.69643697]]..."
1539,1540,GO-20261230916,1781409600000,2026,June,14,Sunday,165,D31,Other,155,Downsview (155),026,Downsview-Roding-CFB (26),-79.486246,43.727717,"{""coordinates"": [[-79.486246045, 43.727716748]..."
1540,1541,GO-20261268185,1781841600000,2026,June,19,Friday,170,D12,Shooting,110,Keelesdale-Eglinton West (110),110,Keelesdale-Eglinton West (110),-79.476094,43.689912,"{""coordinates"": [[-79.476094189, 43.6899117880..."
1541,1542,GO-20261277281,1781928000000,2026,June,20,Saturday,171,D51,Shooting,073,Moss Park (73),073,Moss Park (73),-79.374531,43.657067,"{""coordinates"": [[-79.374530551, 43.657067296]..."

#### Check Data Types

In [93]:
homicide.dtypes

_id                    int64
EVENT_UNIQUE_ID          str
OCC_DATE               int64
OCC_YEAR               int64
OCC_MONTH                str
OCC_DAY                int64
OCC_DOW                  str
OCC_DOY                int64
DIVISION                 str
HOMICIDE_TYPE            str
HOOD_158                 str
NEIGHBOURHOOD_158        str
HOOD_140                 str
NEIGHBOURHOOD_140        str
LONG_WGS84           float64
LAT_WGS84            float64
geometry                 str
dtype: object

#### Check for Missing Data

In [108]:
homicide[homicide["OCC_YEAR"] == 2025].isna().sum()

_id                  0
EVENT_UNIQUE_ID      0
OCC_DATE             0
OCC_YEAR             0
OCC_MONTH            0
OCC_DAY              0
OCC_DOW              0
OCC_DOY              0
DIVISION             0
HOMICIDE_TYPE        0
HOOD_158             0
NEIGHBOURHOOD_158    0
HOOD_140             0
NEIGHBOURHOOD_140    0
LONG_WGS84           0
LAT_WGS84            0
geometry             0
dtype: int64

#### Check Duplicate for Duplicate Rows

In [109]:
print("Homicide duplicates:", homicide.duplicated().sum())

Homicide duplicates: 0

#### Shooting Data Exploration

In [100]:
## Show rows and columns count
print(f"Rows count: {shooting.shape[0]}\nColumns count: {shooting.shape[1]}")

Rows count: 6893
Columns count: 21

In [101]:
shooting.head()

,_id,EVENT_UNIQUE_ID,OCC_DATE,OCC_YEAR,OCC_MONTH,OCC_DOW,OCC_DOY,OCC_DAY,OCC_HOUR,OCC_TIME_RANGE,...,DEATH,INJURIES,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84,EVENT_TYPE,geometry
0,1,GO-2004133803,2004-01-01,2004,January,Thursday,1,1,0,Night,...,NaN,1.0,023,Pelmo Park-Humberlea (23),023,Pelmo Park-Humberlea (23),-79.538218,43.733742,Shooting,"{""coordinates"": [[-79.538218382, 43.7337424510..."
1,2,GO-2004120070,2004-01-03,2004,January,Saturday,3,3,1,Night,...,NaN,NaN,NSA,NSA,NSA,NSA,NaN,NaN,Firearm Discharge,"{""coordinates"": [[5.6843418860808e-14, 5.08888..."
2,3,GO-2004135509,2004-01-04,2004,January,Sunday,4,4,4,Night,...,NaN,2.0,078,Kensington-Chinatown (78),078,Kensington-Chinatown (78),-79.399163,43.656119,Shooting,"{""coordinates"": [[-79.399163136, 43.656119297]..."
3,4,GO-2004126451,2004-01-05,2004,January,Monday,5,5,13,Afternoon,...,NaN,1.0,124,Kennedy Park (124),124,Kennedy Park (124),-79.256039,43.732900,Shooting,"{""coordinates"": [[-79.256038826, 43.7328995840..."
4,5,GO-2004136310,2004-01-06,2004,January,Tuesday,6,6,19,Evening,...,NaN,NaN,146,Malvern East (146),132,Malvern (132),-79.206516,43.808350,Firearm Discharge,"{""coordinates"": [[-79.20651648, 43.80835049400..."

In [102]:
shooting.tail()

,_id,EVENT_UNIQUE_ID,OCC_DATE,OCC_YEAR,OCC_MONTH,OCC_DOW,OCC_DOY,OCC_DAY,OCC_HOUR,OCC_TIME_RANGE,...,DEATH,INJURIES,HOOD_158,NEIGHBOURHOOD_158,HOOD_140,NEIGHBOURHOOD_140,LONG_WGS84,LAT_WGS84,EVENT_TYPE,geometry
6888,6889,GO-20261268185,2026-06-19,2026,June,Friday,170,19,2,Night,...,1.0,NaN,110,Keelesdale-Eglinton West (110),110,Keelesdale-Eglinton West (110),-79.476094,43.689912,Shooting,"{""coordinates"": [[-79.476094189, 43.6899117880..."
6889,6890,GO-20261276344,2026-06-20,2026,June,Saturday,171,20,8,Morning,...,NaN,NaN,078,Kensington-Chinatown (78),078,Kensington-Chinatown (78),-79.394629,43.655767,Firearm Discharge,"{""coordinates"": [[-79.394629039, 43.655767396]..."
6890,6891,GO-20261277281,2026-06-20,2026,June,Saturday,171,20,10,Morning,...,1.0,NaN,073,Moss Park (73),073,Moss Park (73),-79.374531,43.657067,Shooting,"{""coordinates"": [[-79.374530551, 43.657067296]..."
6891,6892,GO-20261275660,2026-06-20,2026,June,Saturday,171,20,0,Night,...,NaN,NaN,002,Mount Olive-Silverstone-Jamestown (2),002,Mount Olive-Silverstone-Jamestown (2),-79.582615,43.733968,Firearm Discharge,"{""coordinates"": [[-79.582614672, 43.733967679]..."
6892,6893,GO-20261303038,2026-06-23,2026,June,Tuesday,174,23,18,Evening,...,NaN,1.0,008,Humber Heights-Westmount (8),008,Humber Heights-Westmount (8),-79.517483,43.692626,Shooting,"{""coordinates"": [[-79.5174825719999, 43.692626..."

#### Check Data Types

In [115]:
shooting.dtypes

_id                    int64
EVENT_UNIQUE_ID          str
OCC_DATE                 str
OCC_YEAR               int64
OCC_MONTH                str
OCC_DOW                  str
OCC_DOY                int64
OCC_DAY                int64
OCC_HOUR               int64
OCC_TIME_RANGE           str
DIVISION                 str
DEATH                float64
INJURIES             float64
HOOD_158                 str
NEIGHBOURHOOD_158        str
HOOD_140                 str
NEIGHBOURHOOD_140        str
LONG_WGS84           float64
LAT_WGS84            float64
EVENT_TYPE               str
geometry                 str
dtype: object

#### Check for Missing Data

In [113]:
shooting[
    (shooting["OCC_YEAR"] == 2025) &
    (shooting["EVENT_TYPE"] == "Shooting")
].isna().sum()

_id                   0
EVENT_UNIQUE_ID       0
OCC_DATE              0
OCC_YEAR              0
OCC_MONTH             0
OCC_DOW               0
OCC_DOY               0
OCC_DAY               0
OCC_HOUR              0
OCC_TIME_RANGE        0
DIVISION              0
DEATH                76
INJURIES             16
HOOD_158              0
NEIGHBOURHOOD_158     0
HOOD_140              0
NEIGHBOURHOOD_140     0
LONG_WGS84            0
LAT_WGS84             0
EVENT_TYPE            0
geometry              0
dtype: int64

Missing values in the `DEATH` and `INJURIES` columns are expected because a shooting event may result in injuries, deaths, or both. A missing value in one of these columns does not necessarily indicate incomplete data; it may simply mean that outcome did not occur for that incident.

#### Check for Duplicate Rows

In [114]:
print("Shooting duplicates:", shooting.duplicated().sum())

Shooting duplicates: 0

### Data Integration and Cleaning Decisions

- The analysis will focus exclusively on crime events that occurred in 2025.
- The crime categories included in the analysis are 
    - `ASSAULT`
    - `AUTHOTHEFT`
    - `BREAKENTER`
    - `HOMICIDE`
    - `ROBBERY`
    - `SHOOTING`
    - `THEFTFROMMV`
    - `THEFTOVER`
- Only the variables required for analysis will be retained, including 
    - `_id`
    - `AREA_NAME`
    - `HOOD_ID`
    - `POPULATION`
- In the homicide and shooting datasets, `HOOD_158` will be converted from a string to an integer and renamed to `HOOD_ID` to ensure consistency across datasets.
- Homicide and shooting data are recorded at the incident level. These records will therefore be aggregated by `HOOD_ID` to calculate the number of occurrences in each neighbourhood.
- After the homicide and shooting datasets are merged with the neighbourhood crime data, remaining missing values for these two crime categories will be replaced with 0, indicating that no recorded homicide or shooting occurred in that neighbourhood during 2025.
- Following Statistics Canada’s standard convention, homicide and shooting rates will be calculated as the number of incidents per 100,000 residents.