# Toronto Crime Data Exploration

This notebook explores the Toronto crime datasets before cleaning and formal analysis.

The goals are to:
- understand the structure of each dataset
- identify missing values and duplicates
- inspect important variables
- compare crime rates across neighbourhoods
- examine patterns over time
- identify cleaning decisions needed before analysis

## 1. Imports

In [23]:
import pandas as pd
import matplotlib.pyplot as plt

## 2. Initial Inspection

In [34]:
crime = pd.read_csv("../data/raw/neighbourhood-crime-rates - 4326.csv")

### 2.1 Dataset Shape and Columns

In [35]:
display(crime.head())
print("Shape:", crime.shape)

,_id,AREA_NAME,HOOD_ID,ASSAULT_2014,ASSAULT_2015,ASSAULT_2016,ASSAULT_2017,ASSAULT_2018,ASSAULT_2019,ASSAULT_2020,...,THEFTOVER_RATE_2018,THEFTOVER_RATE_2019,THEFTOVER_RATE_2020,THEFTOVER_RATE_2021,THEFTOVER_RATE_2022,THEFTOVER_RATE_2023,THEFTOVER_RATE_2024,THEFTOVER_RATE_2025,POPULATION_2025,geometry
0,1,South Eglinton-Davisville,174,55,56,66,73,74,62,74,...,13.797544,13.097577,16.740604,24.216984,11.665436,29.499613,21.188684,20.759809,28902,"{""coordinates"": [[[[-79.3863542900264, 43.6978..."
1,2,North Toronto,173,53,57,47,61,66,84,80,...,36.176834,26.750484,43.862396,11.872959,22.540291,36.945164,30.007502,24.293072,20582,"{""coordinates"": [[[[-79.3974398976879, 43.7069..."
2,3,Dovercourt Village,172,62,65,92,105,106,113,91,...,29.658190,29.775198,22.602276,15.283509,30.555344,22.610792,52.426601,22.850180,13129,"{""coordinates"": [[[[-79.4341164165158, 43.6601..."
3,4,Junction-Wallace Emerson,171,164,159,171,161,163,186,171,...,36.188179,15.985932,36.070698,32.293224,31.383625,33.834587,47.279606,32.400906,27777,"{""coordinates"": [[[[-79.4387032547807, 43.6676..."
4,5,Yonge-Bay Corridor,170,387,521,481,602,576,660,377,...,346.893738,478.723419,258.569733,187.630798,351.821198,337.443207,296.040466,210.071426,16661,"{""coordinates"": [[[[-79.3840431592607, 43.6449..."

Shape: (158, 221)

### 2.2 Data Types

In [ ]:
display(crime.dtypes)

TypeError: unsupported operand type(s) for +: 'numpy.dtypes.Int64DType' and 'StringDtype'

### 2.3 Missing Values

In [47]:
display(crime.isna().sum())

_id                    0
AREA_NAME              0
HOOD_ID                0
ASSAULT_2014           0
ASSAULT_2015           0
                      ..
THEFTOVER_RATE_2023    2
THEFTOVER_RATE_2024    0
THEFTOVER_RATE_2025    0
POPULATION_2025        0
geometry               0
Length: 221, dtype: int64

### 2.4 Duplicate Records

In [32]:
print("Crime duplicates:", crime.duplicated().sum())

Crime duplicates: 0

## 3. Investigation of Missing Crime Data

The neighbourhood crime dataset contains missing values (NaN) for homicide and shooting measures. Since these variables are important to the analysis, separate Toronto Police homicide and shooting datasets are used to investigate and reconstruct the missing information.

## 4. Load Supplementary Homicide and Shooting Data

### 4.1 Homicide Dataset Inspection

## 5. Data Integration and Cleaning Decisions

- Homicide and shooting records are aggregated by neighbourhood ID and year (2025).
- Supplementary data is used to replace or reconstruct missing homicide and shooting values.
- Following the standard definition by StatsCan, crime rate is calculated as the crime count per 100,000 population

In [31]:
summary_stats = clean_crime[
    ["ASSAULT_RATE_2025","AUTOTHEFT_RATE_2025","BREAKENTER_RATE_2025","HOMICIDE_RATE_2025",
     "ROBBERY_RATE_2025","SHOOTING_RATE_2025","THEFTOVER_RATE_2025","THEFTFROMMV_RATE_2025",
    ]
].describe()

display(summary_stats)

,ASSAULT_RATE_2025,AUTOTHEFT_RATE_2025,BREAKENTER_RATE_2025,HOMICIDE_RATE_2025,ROBBERY_RATE_2025,SHOOTING_RATE_2025,THEFTOVER_RATE_2025,THEFTFROMMV_RATE_2025
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,745.495259,216.514823,189.863410,1.476486,76.398116,7.811046,56.830650,207.861621
std,508.854314,149.377388,103.468811,3.117879,46.643476,7.976653,43.388680,117.909391
min,196.463654,16.605089,34.827026,0.000000,7.232750,0.000000,6.022283,36.607689
25%,467.111610,124.401613,113.698444,0.000000,44.613858,0.000000,29.193746,131.426514
50%,636.309937,192.604286,172.802284,0.000000,69.464020,6.461419,46.134712,188.083038
75%,874.586487,265.429695,239.532177,0.000000,95.966524,12.175262,69.588757,242.865898
max,4209.215332,1320.643799,730.282349,16.367952,300.102020,34.405643,274.738281,850.839905